version: '3.3'

services:
  postgres:
    image: 'postgres:11.2'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: ./
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: security_user
      POSTGRES_PASSWORD: security
      SPRING_PROFILES_ACTIVE: postgres