spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true